### ISSUE TITLE
Heroku deployment

### ISSUE THREAD

**Issue by StefanWerW** [dustinblackman/streamroller#2]
I saw that you removed all heroku deployment and info from docs. Is heroku not supported anymore? Or it is another reason? 
I really like this repo, and would love to use on heroku.

Thanks

**Comment by dustinblackman** [comment]
Unfortunately Heroku was never supported, I had committed a branch I had meant not to. Heroku only runs on HTTP, so something like RTMP won't work. I've made a few attempts at converting RTMPT to RTMP and have gotten close in order to support platforms like Heroku, but never a working solution. PRs are welcome.
